Jakt/website/auth.py
from flask import ( 
    Blueprint, flash, render_template, request, url_for, redirect
) 
from werkzeug.security import generate_password_hash,check_password_hash
#from .models import User
from .forms import LoginForm,RegisterForm
from flask_login import login_user, login_required,logout_user
from . import db
from .models import User


#create a blueprint
bp = Blueprint('auth', __name__)


@bp.route('/register', methods=['GET', 'POST'])
def register():
    register = RegisterForm()
    if (register.validate_on_submit() == True):
            uname =register.user_name.data
            pwd = register.password.data
            email=register.email_id.data
            number = register.contact_num.data
            street_address= register.streetAddress.data
            
            #check if a user exists
            u1 = User.query.filter_by(name=uname).first()
            if u1:
                flash('User name already exists, please login')
                return redirect(url_for('auth.login'))
            # don't store the password - create password hash
            pwd_hash = generate_password_hash(pwd)
            #create a new user model object
            new_user = User(name=uname, password_hash=pwd_hash, emailid=email, 
                            contactNum=number, address=street_address)
            db.session.add(new_user)
            db.session.commit()
            #commit to the database and redirect to HTML page
            return redirect(url_for('main.index'))
    #the else is called when there is a get message
    else:
        return render_template('user.html', form=register, heading='Register')


@bp.route('/login', methods=['GET', 'POST'])
def login(): #view function
     print('In Login View function')
     login_form = LoginForm()
     error=None
     if(login_form.validate_on_submit()==True):
         user_name = login_form.user_name.data
         password = login_form.password.data
         u1 = User.query.filter_by(name=user_name).first()
         #If there is no user with that name saved in
         if u1 is None:
             error='Incorrect user name'
         elif not check_password_hash(u1.password_hash, password): # takes the hash and password
             error='Incorrect password'
         if error is None:
             login_user(u1)
             return redirect(url_for('main.index'))
         else:
             flash(error)
     return render_template('user.html', form=login_form, heading='Login')

@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return 'You have been logged out'

Jakt/website/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from .models import Event
import json
import sqlite3

bp = Blueprint('main', __name__)

def getGenreList(): #Retrieve/displaying all available crypto assets/coins
    eventGENRE = [] 
    with open('GenreList.json') as json_file: # open the JSON file 
        genrelist = json.load(json_file) # load the data into an array  
        #display each element in the array 
        for g in genrelist['genrelist']:
            eventGENRE.append(g["name"])
        eventGENRE.sort()
        return eventGENRE 

@bp.route('/')
def index():
    
    event = Event.query.all()
    return render_template('index.html', event=event)

@bp.route('/search')
def search():
    if request.args.get('eventsearch', False):
        print(request.args['eventsearch'])
        evensearch = '%' + request.args['eventsearch'] + '%'
        eventsearch = Event.query.filter(Event.name.like(evensearch)).all()
        return render_template('index.html', event=eventsearch)

    else:
        return redirect(url_for('main.index'))

@bp.route('/genre')
def genre():
    if request.args.get('genresearch', False):
        print(request.args['genresearch'])
        gensearch = '%' + request.args['genresearch'] + '%'
        genresearch = Event.query.filter(Event.genre.like(gensearch)).all()
        return render_template('index.html', event=genresearch)
    else:
        return redirect(url_for('main.index'))

@bp.route('/venue')
def venue():
    if request.args.get('venuesearch', False):
        print(request.args['venuesearch'])
        vensearch = '%' + request.args['venuesearch'] + '%'
        venuesearch = Event.query.filter(Event.venue.like(vensearch)).all()
        return render_template('index.html', event=venuesearch)
    else:
        return redirect(url_for('main.index'))

@bp.route('/status')
def status():
    if request.args.get('statussearch', False):
        print(request.args['statussearch'])
        stasearch = '%' + request.args['statussearch'] + '%'
        statussearch = Event.query.filter(Event.status.like(stasearch)).all()
        return render_template('index.html', event=statussearch)
        
    else:
        return redirect(url_for('main.index'))

Jakt/website/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
   
    <!-- link to CSS file -->
    <!-- <link rel="stylesheet" href="css/style.css"> -->

    <link rel="stylesheet" href="/static/css/style.css">

    <title>Music Booking Website</title>

  </head>
  <body class = "standard font">
<!-- need to make register, log in and log out functional  -->
    <header>

      <nav class="navbar navbar-expand-lg inverse">
        <div class="container-fluid">
          <h1>Jakt</h1>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon">
              <i class="fa fa-navicon" style="color:#fff; font-size:28px;"></i>
            </span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                <a class="nav-link active inverse" aria-current="page" href="{{ url_for('main.index') }}">Browse Events</a>
              </li>
              {% if current_user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link inverse" href="{{ url_for('event.create') }}">Create an Event</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link inverse" href="{{ url_for('purchased.purchased') }}">Booking History</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link inverse" href="{{ url_for('auth.logout') }}">Log Out</a>
                </li>
              {% else %}
                <!-- make this dynamic - refer to tut base.html -->
                <!-- show log out to logged in users -->
                <!-- show register and log in to other users -->
                <!-- need authentication working first -->
                <li class="nav-item">
                  <a class="nav-link inverse" href="{{ url_for('auth.register') }}">Register</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link inverse" href="{{ url_for('auth.login') }}">Log in</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>

    </header>

    {% block content %}
   {% endblock %}

    <footer class="standard">
      Copyright Judah, Adele, Kael, Talei
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
         integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
         crossorigin="anonymous"></script>
  </body>

</html>

Jakt/website/templates/history.html
{% extends 'base.html' %}

{% import "bootstrap/form.html" as wtf %}

{% block content %}

<main class="standard">
    <div class="container-fluid">
        <h1 class = "p-3">Booking History</h1>
        <div class="row">
        {% for purchase in purchased %}
        {% if purchase.user_id == current_id %}
        <div class="col-12 col-sm-12 col-md-6 p-3 p-3 d-flex justify-content-start">
            <!-- card 1 -->
            <div class="card text-center">
                <div class="card-header inverse">
                    <!-- make content dynamic - refer to tut show.html -->
                  <b>Booking ID: {{purchase.id}}</b>
                </div>
                <div class="card-body standard">
                    <div class="container">
                        <div class="row">
                          <div class="col-12 col-xl-6">
                            <img src="{{purchase.image}}" width = "100%">
                          </div>
                          <div class="col-12 col-xl-6">
                            <!-- make content dynamic - refer to tut show.html -->
                            <h5 class="card-title p-3">{{purchase.event}}</h5>
                            <br>
                            <p>Number of tickets: {{purchase.ticket_number}}</p>
                            </div>
                        </div>
                      </div>
                </div>
                <div class="card-footer inverse">
                    <!-- make content dynamic - refer to tut show.html -->
                    <i>Booked on {{purchase.purchased_on}}</i>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
        </div>
    </div>
</main>
{% endblock %}

Jakt/website/templates/index.html
{% extends 'base.html' %}

{% block content %}

    <!-- first row -->
    <div class="row">
        <div class="col-sm-12">




          
            <div id="carouselExampleControls" data-bs-ride="carousel" class="carousel slide container-fluid p-3">
                <!-- <div class="carousel-indicators">
                  {% for event in event %}
                  <button type="button" data-bs-target="carouselExampleControls" data-bs-slide-to="{{ loop.index }}" {% if loop.index == 1 %} class="active" {% endif %}></button>
                  {% endfor %}
                </div> -->
                <div class="carousel-inner">
                  {% for event in event %}
                    <div class="carousel-item {% if loop.index == 1 %} active {% endif %}">
                      <img src="{{ event.image }}" class="d-block w-100">
                      <div class="carousel-caption d-none d-md-block">
                        <p>{{ event.name }}</p>
                      </div>
                    </div>
                  {% endfor %}
               </div>
                <!-- <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button> -->
            </div>


          </div>
        </div> <!-- row end -->

        <!-- second row -->
        <div class="row">
            <div class="col-12 col-sm-6" align="center">

                <!-- search bar - refer to tut index.html and views.py-->
              <form class="form-inline d-flex flex-nowrap" action="{{url_for('main.search')}}">
                <input type="text" name="eventsearch" class="form-control flex-grow-1 my-1 mr-sm-2" id="SearchForm" placeholder="Search Events">
                <button type="submit" class="flex-shrink-1 btn btn-change my-1">Submit</button>
              </form>
            </div>
            
            <br><br>
            
            <!-- off canvas - make sort buttons work - similar to search function? -->
            <div class="col-12 col-sm-6" align="center">
              <button class="flex-shrink-1 btn btn-change my-1" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">Sort More</button>

              <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
                <div class="offcanvas-header inverse">
                  <h5 class="offcanvas-title" id="offcanvasRightLabel">Sort Options</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body standard">
                  <div class="container text-center">
                  </div>
                  <form>
                    <div class="row">
                      <div class="col">
                        <form class="form-inline d-flex flex-nowrap" action="{{url_for('main.index')}}"></form>
                          <button type="submit" class="flex-shrink-1 btn btn-change my-1">Reset Search</button>
                        </form>
                      </div>
                    </div>
                    <br>
                    <div class="row">
                      <div class="col">
                        <h5>Search Genre</h5>
                        <form class="form-inline d-flex flex-nowrap" action="{{url_for('main.genre')}}">
                          <select name="genresearch" id="genresearch" class="form-control flex-grow-1 my-1 mr-sm-2">
                            <option value="Pop">Pop</option>
                            <option value="Rock">Rock</option>
                            <option value="Jazz">Jazz</option>
                            <option value="Country">Country</option>
                            <option value="Electronic">Electronic</option>
                            <option value="Metal">Metal</option>
                          </select>
                          <button type="submit" class="flex-shrink-1 btn btn-change my-1">Submit</button>
                        </form>
                      </div>
                    </div>

                    <br>
                    <div class="row">
                      <div class="col">
                        <h5>Search Venue</h5>
                        <form class="form-inline d-flex flex-nowrap" action="{{url_for('main.venue')}}">
                          <input type="text" name="venuesearch" class="form-control flex-grow-1 my-1 mr-sm-2" id="SearchForm">
                          <button type="submit" class="flex-shrink-1 btn btn-change my-1">Submit</button>
                        </form>
                      </div>
                    </div>
                    
                    <br>
                    <div class="row">
                      <div class="col">
                        <h5>Search Status</h5>
                        <form class="form-inline d-flex flex-nowrap" action="{{url_for('main.status')}}">
                          <select name="statussearch" id="statussearch" class="form-control flex-grow-1 my-1 mr-sm-2">
                            <option value="Open">Open</option>
                            <option value="Sold-out">Sold-Out</option>
                            <option value="Cancelled">Cancelled</option>
                            <option value="Unpublished">Unpublished</option>
                          </select>
                          <button type="submit" class="flex-shrink-1 btn btn-change my-1">Submit</button>
                        </form>
                      </div>
                    </div>
                    <br>
                    </div>
                  </div>
                </div>
              </div>
            </form>
        </div> <!-- row end --> 

        <!-- third row -->
        <div class="row">
            <div class="col-12">
              <h2 class="p-3"> Browse All Events: </h2>
            </div>
        </div><!-- row end --> 

        <!-- fourth row -->

        <!-- make cards dynamic - refer to tut index.html (and destinations.py?) -->
        <div class="container">
            <div class="row">
              {% for event in event %}
              {% if event.status != "Unpublished" %}
              <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3 p-3 p-3 d-flex justify-content-start">
                <div class="inverse card mx-3" style="width: 100%;">
                  <img src={{event.image}} class="card-img-top" alt="event picture">
                  <div class="card-body">
                    <p class="card-text">
                    <h2>{{event.name}}</h2>
                    <span class="badge standard">{{event.status}}</span>
                    <br><br>
                    Venue: {{event.venue}}
                    <br>
                    Date: {{event.date}}
                    <br>
                    Start Time: {{event.start_time}}
                    <br>
                    End Time: {{event.end_time}}
                    <br><br>
                    </p>
                  </div>
                  <div class="card-footer mx-auto justify-content-center">
                    {% if event.user == current_user %}
                    <a href="{{url_for('event.edit', event=event.id)}}" class="btn standard" role="button">Edit Event</a>
                    <br><br>
                    {% endif %}
                    <a href="{{url_for('event.show', id=event.id)}}" class="btn standard" href="details.html" role="button">View Details</a>
                  </div>
                </div>
              </div>
              {% elif ((event.status == "Unpublished") and (event.user == current_user)) %}
              <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3 p-3 p-3 d-flex justify-content-start">
                <div class="inverse card mx-3" style="width: 100%;">
                  <img src={{event.image}} class="card-img-top" alt="event picture">
                  <div class="card-body">
                    <p class="card-text">
                    <h2>{{event.name}}</h2>
                    <span class="badge standard">{{event.status}}</span>
                    <br><br>
                    Venue: {{event.venue}}
                    <br>
                    Date: {{event.date}}
                    <br>
                    Start Time: {{event.start_time}}
                    <br>
                    End Time: {{event.end_time}}
                    <br><br>
                    </p>
                  </div>
                  <div class="card-footer mx-auto justify-content-center">
                    <a href="{{url_for('event.edit', event=event.id)}}" class="btn standard" role="button">Edit Event</a>
                    <br><br>
                    <a href="{{url_for('event.show', id=event.id)}}" class="btn standard" role="button">View Details</a>
                  </div>
                </div>
              </div>
              {% else %}
              {% endif %}
              {% endfor %}
            </div>
        </div><!-- row end --> 
</main>

{% endblock %}

Jakt/website/templates/user.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

<div class="page-header">
    <h4>{{heading}}</h4>
</div>



<div class="container-fluid">
{% with messages = get_flashed_messages() %}
{% if messages %}
    {% for message in get_flashed_messages() %}
    <div class ="alert inverse">
        <button type="button" class="close" data-bs-dismiss="alert" aria-label="close">x</button>
        {{message}}
    </div>
    {% endfor %}
{% endif %}
{% endwith %}

</div>



<!-- Form rendering is simple and easy if using bootstrap -->
<div class="col-md-6">
{{wtf.quick_form(form)}}
</div>

<!-- When you have login form, then do show the user a link to register -->
{% if heading|lower =='login' %}
<div class="col-md-4">
    <p>New user? <a href="{{ url_for('auth.register') }}">Click here to register</a>.</p>
</div>
{% endif %}

{% endblock %}